name: Deploy Architecture

on:
  push:
    branches:
      - main

# on:
#   workflow_run:
#     workflows: ["Initialize Terraform Backend"]
#     types:
#       - completed
jobs:
  terraform-init:
    runs-on: ubuntu-latest
    environment: aws
    
    env:
      TF_VAR_branch_env: "main" 
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      TF_VAR_aws_region: "us-east-1"
      TF_VAR_role: "LabRole"
      TF_VAR_ecs_task_cpu_architecture: "ARM_64"
      AWS_REGION: "us-east-1"

      AWS_BUCKET_NAME_TERRAFORM_STATE: ${{ secrets.S3_TERRAFORM_STATE_NAME }}
      AWS_DYNAMODB_NAME: ${{ secrets.DYNAMODB_TERRAFORM_LOCK_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Create Terraform backend configuration Dev
      run: |
        cd LendARead2-AWS/terraform/dev
        sed "s|\${bucket}|$AWS_BUCKET_NAME_TERRAFORM_STATE|g" backend.tpl > backend.tf
        sed -i "s|\${region}|$AWS_REGION|g" backend.tf
        sed -i "s|\${dynamodb_table}|$AWS_DYNAMODB_NAME|g" backend.tf

    - name: Create Terraform backend configuration QA
      run: |
        cd LendARead2-AWS/terraform/qa
        sed "s|\${bucket}|$AWS_BUCKET_NAME_TERRAFORM_STATE|g" backend.tpl > backend.tf
        sed -i "s|\${region}|$AWS_REGION|g" backend.tf
        sed -i "s|\${dynamodb_table}|$AWS_DYNAMODB_NAME|g" backend.tf


    - name: Create Terraform backend configuration Prod
      run: |
        cd LendARead2-AWS/terraform/prod
        sed "s|\${bucket}|$AWS_BUCKET_NAME_TERRAFORM_STATE|g" backend.tpl > backend.tf
        sed -i "s|\${region}|$AWS_REGION|g" backend.tf
        sed -i "s|\${dynamodb_table}|$AWS_DYNAMODB_NAME|g" backend.tf

    - name: Initialize Dev Enviroment
      run: |
        cd LendARead2-AWS/terraform/dev
        echo "Current directory contents:"
        ls
        terraform init
        terraform apply -auto-approve -var-file="dev.tfvars"

    - name: Initialize QA Enviroment
      run: |
        cd LendARead2-AWS/terraform/qa
        terraform init
        terraform apply -auto-approve -var-file=qa.tfvars 


    - name: Initialize Prod Enviroment
      run: |
        cd LendARead2-AWS/terraform/prod
        terraform init
        terraform apply -auto-approve -var-fil=prod.tfvars  
