name: Deploy Image and Force ECS deploy it

on:
  push:
    branches:
      - main

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    environment: aws
    
    env:
      BRANCH: "main" 
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: "us-east-1"

      AWS_BUCKET_NAME_TERRAFORM_STATE: ${{ secrets.S3_TERRAFORM_STATE_NAME }}
      AWS_ECR_URL: "516697223383.dkr.ecr.us-east-1.amazonaws.com"
      VERSION: "latest"
      AWS_DYNAMODB_NAME: ${{ secrets.DYNAMODB_TERRAFORM_LOCK_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Create and Deploy Image to ECR
      run: |
          cd LendARead2-AWS/terraform/modules/main
          aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ECR_URL}
          docker build --build-arg BRANCH_NAME=${BRANCH} -t ${AWS_ECR_URL}/lendaread_ecr_region:${VERSION} .
          docker push ${AWS_ECR_URL}/lendaread_ecr_region:${VERSION}

