name: Initialize Terraform Backend

on:
  push:
    tags:
      - init

jobs:
  terraform-init:
    runs-on: ubuntu-latest
    environment: aws
    
    env:
      AWS_DEFAULT_REGION: us-east-1 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List repository contents
      run: ls -R

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Initialize Terraform backend resources
      run: |
        cd "LendARead2-AWS/terraform/init"
        terraform init
        terraform apply --auto-approve
